title: Somerset Rural Music School

collections:
    news:
        output: true
        permalink: /news/:year/:month/:title

# Build settings
markdown: kramdown
permalink:    pretty

gems:
  - jekyll-redirect-from